openapi: 3.0.3
info:
  title: SoHappyToCyou API Documentation
  description: SoHappyToCyou API Documentation
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /auth/login:
    post:
      summary: Authenticating user
      description: Authenticating user
      requestBody:
        required: true
      response:
        '200':
          description: Returning authentication session
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: string

  
